# Generated by Django 3.1 on 2020-09-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_records',
            name='date',
            field=models.DateField(),
        ),
    ]
